networks:
  rtpi_bridge:
    driver: bridge
  rtpi_host:
    driver: host
  kasm_default_network:
    driver: bridge
  rtpi_none:
    driver: "null"
  sysreptor_default:
    driver: bridge
  npm_network:
    driver: bridge

volumes:
  # Named volumes for persistence
  sysreptor-app-data:
    driver: local
  sysreptor-db-data:
    driver: local
  sysreptor-caddy-data:
    driver: local
  kasm_db_1.15.0:
    driver: local
  portainer_data:
    driver: local
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local
  npm_mysql:
    driver: local
  empire_data:
    driver: local
  registry_data:
    driver: local

services:
  # Main orchestrator container (rtpi-pen)
  rtpi-pen:
    build:
      context: .
      dockerfile: Dockerfile
    image: cmndcntrl/rtpi-pen:latest
    container_name: rtpi-pen
    restart: unless-stopped
    networks:
      - rtpi_bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./configs:/opt/rtpi-pen/configs:ro
      - ./setup:/opt/rtpi-pen/setup:ro
    command: ["portainer"]
    ports:
      - "9443:9443" # Portainer HTTPS UI

  # Nginx Proxy Manager
  npm_app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm_app
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP Port
      - '81:81'   # Admin Web Port
      - '443:443' # Public HTTPS Port
    environment:
      DB_MYSQL_HOST: "npm_db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "T0t4llyCh4ng3Th15P455word"
      DB_MYSQL_NAME: "npm"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - npm_network
      - rtpi_bridge
    depends_on:
      - npm_db

  npm_db:
    image: 'jc21/mariadb-aria:latest'
    container_name: npm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'T0t4llyCh4ng3Th15P455word'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'T0t4llyCh4ng3Th15P455word'
    volumes:
      - npm_mysql:/var/lib/mysql
    networks:
      - npm_network

  # Docker Registry
  registry:
    image: registry:latest
    container_name: local-registry
    restart: unless-stopped
    networks:
      - rtpi_bridge
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

  # Kasm Workspaces stack
  kasm_agent:
    image: kasmweb/agent:1.15.0
    container_name: kasm_agent
    restart: unless-stopped
    networks:
      - kasm_default_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - kasm_db_1.15.0:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /opt/kasm/1.15.0/conf/nginx:/etc/nginx/conf.d:rw
      - /opt/kasm/1.15.0:/opt/kasm/current:rw

  kasm_api:
    image: kasmweb/api:1.15.0
    container_name: kasm_api
    restart: unless-stopped
    networks:
      - kasm_default_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /opt/kasm/1.15.0:/opt/kasm/current:rw
      - /opt/kasm/1.15.0/tmp/api:/tmp:rw
    depends_on:
      - kasm_db

  kasm_db:
    image: postgres:12-alpine
    container_name: kasm_db
    restart: unless-stopped
    networks:
      - kasm_default_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - kasm_db_1.15.0:/var/lib/postgresql/data
      - /opt/kasm/1.15.0/log/postgres:/var/log/postgres:rw
      - /opt/kasm/1.15.0/conf/database/data.sql:/docker-entrypoint-initdb.d/data.sql:rw
      - /opt/kasm/1.15.0/certs/db_server.crt:/etc/ssl/certs/db_server.crt:rw
      - /opt/kasm/1.15.0/certs/db_server.key:/etc/ssl/certs/db_server.key:rw
      - /opt/kasm/1.15.0/conf/database:/tmp:rw
      - /opt/kasm/1.15.0/conf/database/pg_hba.conf:/var/lib/postgresql/conf/pg_hba.conf:rw
      - /opt/kasm/1.15.0/conf/database/postgresql.conf:/var/lib/postgresql/conf/postgresql.conf:rw
    command: postgres -c ssl=on -c ssl_cert_file=/etc/ssl/certs/db_server.crt -c ssl_key_file=/etc/ssl/certs/db_server.key -c config_file=/var/lib/postgresql/conf/postgresql.conf -c hba_file=/var/lib/postgresql/conf/pg_hba.conf

  kasm_guac:
    image: kasmweb/kasm-guac:1.15.0
    container_name: kasm_guac
    restart: unless-stopped
    networks:
      - kasm_default_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /opt/kasm/1.15.0:/opt/kasm/current:rw
      - /opt/kasm/1.15.0/tmp/guac:/tmp:rw

  kasm_manager:
    image: kasmweb/manager:1.15.0
    container_name: kasm_manager
    restart: unless-stopped
    networks:
      - kasm_default_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /opt/kasm/1.15.0:/opt/kasm/current:rw
    depends_on:
      - kasm_db

  kasm_proxy:
    image: kasmweb/nginx:1.25.3
    container_name: kasm_proxy
    restart: unless-stopped
    networks:
      - kasm_default_network
      - rtpi_bridge
    ports:
      - "8443:443"  # Changed from 443:443 to avoid conflict with npm_app
    volumes:
      - /opt/kasm/1.15.0/conf/nginx:/etc/nginx/conf.d:ro
      - /opt/kasm/1.15.0/certs/kasm_nginx.crt:/etc/ssl/certs/kasm_nginx.crt:rw
      - /opt/kasm/1.15.0/certs/kasm_nginx.key:/etc/ssl/private/kasm_nginx.key:rw
      - /opt/kasm/1.15.0/www:/srv/www:ro
      - /opt/kasm/1.15.0/log/logrotate:/var/log/external/logrotate:rw
      - /opt/kasm/1.15.0/log/nginx:/var/log/external/nginx:rw
    depends_on:
      - kasm_api
      - kasm_manager
      - kasm_share
      - kasm_guac
      - kasm_agent

  kasm_redis:
    image: redis:5-alpine
    container_name: kasm_redis
    restart: unless-stopped
    networks:
      - kasm_default_network
    command: redis-server --appendonly yes
    volumes:
      - kasm_db_1.15.0:/data

  kasm_share:
    image: kasmweb/share:1.15.0
    container_name: kasm_share
    restart: unless-stopped
    networks:
      - kasm_default_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /opt/kasm/1.15.0:/opt/kasm/current:rw
    depends_on:
      - kasm_db
      - kasm_redis

  # Empire C2 framework
  ps-empire:
    image: bcsecurity/empire:latest
    container_name: ps-empire
    restart: unless-stopped
    networks:
      - rtpi_bridge
    ports:
      - "1337:1337"
      - "5000:5000"
    volumes:
      - empire_data:/empire
    command: ./ps-empire server

  # Node.js service
  node:
    image: node:latest
    container_name: node
    restart: unless-stopped
    networks:
      - rtpi_bridge
    ports:
      - "3500:3500"

  # SysReptor stack
  sysreptor-app:
    image: syslifters/sysreptor:2025.37
    container_name: sysreptor-app
    restart: unless-stopped
    networks:
      - sysreptor_default
      - rtpi_bridge
    ports:
      - "9000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - sysreptor-app-data:/app/data
    depends_on:
      - sysreptor-db
      - sysreptor-redis
    command: /bin/bash /app/api/start.sh
    env_file:
      - ./configs/rtpi-sysreptor/app.env

  sysreptor-caddy:
    image: caddy:latest
    container_name: sysreptor-caddy
    restart: unless-stopped
    networks:
      - sysreptor_default
      - rtpi_bridge
    ports:
      - "7777:7777"
    volumes:
      - sysreptor-caddy-data:/data
      - ./configs/rtpi-sysreptor/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    command: caddy reverse-proxy --from :7777 --to sysreptor-app:8000

  sysreptor-db:
    image: postgres:14
    container_name: sysreptor-db
    restart: unless-stopped
    networks:
      - sysreptor_default
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - sysreptor-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sysreptorpassword
      - POSTGRES_USER=sysreptor
      - POSTGRES_DB=sysreptor

  sysreptor-redis:
    image: bitnami/redis:7.2
    container_name: sysreptor-redis
    restart: unless-stopped
    networks:
      - sysreptor_default
    environment:
      - REDIS_PASSWORD=sysreptorredispassword
